dropItemsTypeList:
- [Word, DropLabel]
- [translation, DropLabel]
- [cyrillicTrans, DropLabel]
- [transcription, DropLabel]
- [spoilerExample, SpoilerExampleLabel]
- [example2, DropLabel]
- [input, InputEdit]
- [image, ImageLabel, ./resources/icons/base/photo_landscape2.png, iconAndText]

