dropItemsTypeList:
- [Word, DropLabel]
- [translation, DropLabel]
- [cyrillicTrans, DropLabel]
- [example, DropLabel]
- [example2, DropLabel]
- [input, InputEdit]
- [OnlyIcon, ClassWidget, ./resources/icons/base/icon_gift_alt.png, onlyIcon]

