choosedict:
    checkedDicts:
    - days of the week
    soundTypeList:
    - Word
    - spoilerExample
core:
    autoSound: false
    cycle: true
    lastFileDict: E:/pyprojects/ling/lingvo/data/slovar1/slovar1.xlsx
currentStyle: base
customizeLabel:
    Word: AAAAAAAAAAAAA
    Word_22050510028028864300324: AAAAAAAAAAAAA
    example: AAAAAAAAAAAAA
    example2: AAAAAAAAAAAAA
    lb1: lb1
    translation: AAAAAAAAAAAAA
ui:
    currentStackWidget: view
    fullScreen: false
    mainWindowSize:
    - 840
    - 880
    viewCardSize:
    - 670
    - 810
