card:
    content:
        back:
            bottom: []
            center: []
            top: []
        front:
            bottom:
            - cyrillicTranscription_DropLabel
            center:
            - translation_DropLabel
            - cyrillicTranscription_DropLabel
            top:
            - Word_DropLabel
    dropItems:
    - Word_DropLabel
    - translation_DropLabel
    - cyrillicTranscription_DropLabel
    - examples_DropLabel
    - input_InputEdit
choosedict:
    checkedDicts:
    - slovar2
core:
    cycle: true
    lastFileDict: E:/pyprojects/ling/lingvo/data/slovar1/slovar1.xlsx
ui:
    currentStackWidget: view
    startSize:
    - 600
    - 600
