card:
    content:
        back:
            bottom:
            - example_DropLabel
            center:
            - cyrillicTranscription_DropLabel
            top:
            - Word_DropLabel
        front:
            bottom: []
            center:
            - translation_DropLabel
            top: []
    dropItems:
    - Word_DropLabel
    - translation_DropLabel
    - cyrillicTranscription_DropLabel
    - example_DropLabel
    - example2_DropLabel
    - input_InputEdit
choosedict:
    checkedDicts:
    - slovar1
core:
    cycle: true
    lastFileDict: E:/pyprojects/ling/lingvo/data/slovar1/slovar1.xlsx
currentStyle: base
ui:
    currentStackWidget: view
    startSize:
    - 600
    - 600
