card:
    content:
        back:
            bottom: []
            center: []
            top: []
        front:
            bottom: []
            center: []
            top:
            - Word_22050510028028864300324_DropLabel
    dropItems:
    - Word_DropLabel
    - translation_DropLabel
    - cyrillicTranscription_DropLabel
    - example_DropLabel
    - example2_DropLabel
    - input_InputEdit
choosedict:
    checkedDicts:
    - slovar1
core:
    cycle: true
    lastFileDict: E:/pyprojects/ling/lingvo/data/slovar1/slovar1.xlsx
currentStyle: base
customizeLabel:
    Word: AAAAAAAAAAAAA
    Word_22050510028028864300324: AAAAAAAAAAAAA
    lb1: lb1
ui:
    currentStackWidget: view
    startSize:
    - 600
    - 600
