core:
    cycle: true
    lastFileDict: E:/pyprojects/ling/lingvo/data/slovar1/slovar1.xlsx
ui:
    startSize:
    - 600
    - 600
card:
    content:
        front:
            top: []
            center: [Пример]
            bottom: []
        back:
            top: [Word]
            center: [Транскрипция]
            bottom: [Пример, Пример]

